/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TheConnectstoSchema = "none" | "output" | "b" | "b + c" | "b + c + d" | "b + d" | "c" | "c + d" | "d";
export type TheWavetypeSchema = "sine" | "square" | "sawtooth" | "triangle";
export type TheRatioSchema = number;
export type TheFrequencyModeSchema = "ratio" | "fixed";
export type TheFixedFrequencySchema = number;
export type TheDetuneSchema = number;
export type TheModulationfactorSchema = number;
export type TheFeedbackSchema = number;
export type TheAttacktimeSchema = number;
export type TheDecayTimeSchema = number;
export type TheSustainlevelSchema = number;
export type TheReleasetimeSchema = number;
export type TheModifierSchema = number;
export type TheAttacktimeSchema1 = number;
export type TheDecayTimeSchema1 = number;
export type TheSustainlevelSchema1 = number;
export type TheReleasetimeSchema1 = number;
export type TheModifierSchema1 = number;
export type TheConnectstoSchema1 = "none" | "output" | "a" | "a + c" | "a + c + d" | "a + d" | "c" | "c + d" | "d";
export type TheWavetypeSchema1 = "sine" | "square" | "sawtooth" | "triangle";
export type TheRatioSchema1 = number;
export type TheDetuneSchema1 = number;
export type TheFrequencyModeSchema1 = "ratio" | "fixed";
export type TheFixedFrequencySchema1 = number;
export type TheModulationfactorSchema1 = number;
export type TheFeedbackSchema1 = number;
export type TheAttacktimeSchema2 = number;
export type TheDecayTimeSchema2 = number;
export type TheSustainlevelSchema2 = number;
export type TheReleasetimeSchema2 = number;
export type TheModifierSchema2 = number;
export type TheAttacktimeSchema3 = number;
export type TheDecayTimeSchema3 = number;
export type TheSustainlevelSchema3 = number;
export type TheReleasetimeSchema3 = number;
export type TheModifierSchema3 = number;
export type TheConnectstoSchema2 = "none" | "output" | "a" | "a + b" | "a + b + d" | "a + d" | "b" | "b + d" | "d";
export type TheWavetypeSchema2 = "sine" | "square" | "sawtooth" | "triangle";
export type TheRatioSchema2 = number;
export type TheDetuneSchema2 = number;
export type TheFrequencyModeSchema2 = "ratio" | "fixed";
export type TheFixedFrequencySchema2 = number;
export type TheModulationfactorSchema2 = number;
export type TheFeedbackSchema2 = number;
export type TheAttacktimeSchema4 = number;
export type TheDecayTimeSchema4 = number;
export type TheSustainlevelSchema4 = number;
export type TheReleasetimeSchema4 = number;
export type TheModifierSchema4 = number;
export type TheAttacktimeSchema5 = number;
export type TheDecayTimeSchema5 = number;
export type TheSustainlevelSchema5 = number;
export type TheReleasetimeSchema5 = number;
export type TheModifierSchema5 = number;
export type TheConnectstoSchema3 = "none" | "output" | "a" | "a + b" | "a + b + c" | "a + c" | "b" | "b + c" | "c";
export type TheWavetypeSchema3 = "sine" | "square" | "sawtooth" | "triangle";
export type TheRatioSchema3 = number;
export type TheDetuneSchema3 = number;
export type TheFrequencyModeSchema3 = "ratio" | "fixed";
export type TheFixedFrequencySchema3 = number;
export type TheModulationfactorSchema3 = number;
export type TheFeedbackSchema3 = number;
export type TheAttacktimeSchema6 = number;
export type TheDecayTimeSchema6 = number;
export type TheSustainlevelSchema6 = number;
export type TheReleasetimeSchema6 = number;
export type TheModifierSchema6 = number;
export type TheAttacktimeSchema7 = number;
export type TheDecayTimeSchema7 = number;
export type TheSustainlevelSchema7 = number;
export type TheReleasetimeSchema7 = number;
export type TheModifierSchema7 = number;

export interface TheRootSchema {
  a: TheASchema;
  b: TheBSchema;
  c: TheCSchema;
  d: TheDSchema;
  [k: string]: any;
}
export interface TheASchema {
  connectsTo: TheConnectstoSchema;
  waveType: TheWavetypeSchema;
  ratio: TheRatioSchema;
  frequencyMode: TheFrequencyModeSchema;
  fixedFrequency: TheFixedFrequencySchema;
  detune: TheDetuneSchema;
  modulationFactor: TheModulationfactorSchema;
  feedback: TheFeedbackSchema;
  ampEnv: TheAmpenvSchema;
  pitchEnv: ThePitchenvSchema;
  [k: string]: any;
}
export interface TheAmpenvSchema {
  attackTime: TheAttacktimeSchema;
  decayTime: TheDecayTimeSchema;
  sustainLevel: TheSustainlevelSchema;
  releaseTime: TheReleasetimeSchema;
  modifier: TheModifierSchema;
  [k: string]: any;
}
export interface ThePitchenvSchema {
  attackTime: TheAttacktimeSchema1;
  decayTime: TheDecayTimeSchema1;
  sustainLevel: TheSustainlevelSchema1;
  releaseTime: TheReleasetimeSchema1;
  modifier: TheModifierSchema1;
  [k: string]: any;
}
export interface TheBSchema {
  connectsTo: TheConnectstoSchema1;
  waveType: TheWavetypeSchema1;
  ratio: TheRatioSchema1;
  detune: TheDetuneSchema1;
  frequencyMode: TheFrequencyModeSchema1;
  fixedFrequency: TheFixedFrequencySchema1;
  modulationFactor: TheModulationfactorSchema1;
  feedback: TheFeedbackSchema1;
  ampEnv: TheAmpenvSchema1;
  pitchEnv: ThePitchenvSchema1;
  [k: string]: any;
}
export interface TheAmpenvSchema1 {
  attackTime: TheAttacktimeSchema2;
  decayTime: TheDecayTimeSchema2;
  sustainLevel: TheSustainlevelSchema2;
  releaseTime: TheReleasetimeSchema2;
  modifier: TheModifierSchema2;
  [k: string]: any;
}
export interface ThePitchenvSchema1 {
  attackTime: TheAttacktimeSchema3;
  decayTime: TheDecayTimeSchema3;
  sustainLevel: TheSustainlevelSchema3;
  releaseTime: TheReleasetimeSchema3;
  modifier: TheModifierSchema3;
  [k: string]: any;
}
export interface TheCSchema {
  connectsTo: TheConnectstoSchema2;
  waveType: TheWavetypeSchema2;
  ratio: TheRatioSchema2;
  detune: TheDetuneSchema2;
  frequencyMode: TheFrequencyModeSchema2;
  fixedFrequency: TheFixedFrequencySchema2;
  modulationFactor: TheModulationfactorSchema2;
  feedback: TheFeedbackSchema2;
  ampEnv: TheAmpenvSchema2;
  pitchEnv: ThePitchenvSchema2;
  [k: string]: any;
}
export interface TheAmpenvSchema2 {
  attackTime: TheAttacktimeSchema4;
  decayTime: TheDecayTimeSchema4;
  sustainLevel: TheSustainlevelSchema4;
  releaseTime: TheReleasetimeSchema4;
  modifier: TheModifierSchema4;
  [k: string]: any;
}
export interface ThePitchenvSchema2 {
  attackTime: TheAttacktimeSchema5;
  decayTime: TheDecayTimeSchema5;
  sustainLevel: TheSustainlevelSchema5;
  releaseTime: TheReleasetimeSchema5;
  modifier: TheModifierSchema5;
  [k: string]: any;
}
export interface TheDSchema {
  connectsTo: TheConnectstoSchema3;
  waveType: TheWavetypeSchema3;
  ratio: TheRatioSchema3;
  detune: TheDetuneSchema3;
  frequencyMode: TheFrequencyModeSchema3;
  fixedFrequency: TheFixedFrequencySchema3;
  modulationFactor: TheModulationfactorSchema3;
  feedback: TheFeedbackSchema3;
  ampEnv: TheAmpenvSchema3;
  pitchEnv: ThePitchenvSchema3;
  [k: string]: any;
}
export interface TheAmpenvSchema3 {
  attackTime: TheAttacktimeSchema6;
  decayTime: TheDecayTimeSchema6;
  sustainLevel: TheSustainlevelSchema6;
  releaseTime: TheReleasetimeSchema6;
  modifier: TheModifierSchema6;
  [k: string]: any;
}
export interface ThePitchenvSchema3 {
  attackTime: TheAttacktimeSchema7;
  decayTime: TheDecayTimeSchema7;
  sustainLevel: TheSustainlevelSchema7;
  releaseTime: TheReleasetimeSchema7;
  modifier: TheModifierSchema7;
  [k: string]: any;
}
